# Generated by Django 2.2.10 on 2020-02-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180406_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
